spring:
  datasource:
    password: ${db.password:12345}
    url: jdbc:mysql://${db.host:mysqldb}:${db.port:3306}/${db.name:person}
    username: ${db.username:root}
  jpa:
    hibernate:
      ddl-auto: create-drop
